{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location"]}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting"]]},"abstract":[{"text":"The location where the error was thrown.","type":"text"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location","interfaceLanguage":"swift"},"metadata":{"title":"location","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"NIOHTTP2"}],"role":"symbol","externalID":"s:8NIOHTTP20A6ErrorsO24PushInViolationOfSettingV8locationSSvp","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting":{"kind":"symbol","abstract":[{"type":"text","text":"An attempt was made to push a stream, even though the settings forbid it."}],"title":"NIOHTTP2Errors.PushInViolationOfSetting","navigatorTitle":[{"kind":"identifier","text":"PushInViolationOfSetting"}],"role":"symbol","url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushInViolationOfSetting"}],"type":"topic"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","title":"NIOHTTP2","kind":"symbol","role":"collection","url":"\/documentation\/niohttp2","type":"topic","abstract":[]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors":{"navigatorTitle":[{"text":"NIOHTTP2Errors","kind":"identifier"}],"abstract":[{"text":"Errors that ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2"},{"text":" raises when handling HTTP\/2 connections.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NIOHTTP2Errors","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/niohttp2\/niohttp2errors","role":"symbol","title":"NIOHTTP2Errors","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","type":"topic"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting/location":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The location where the error was thrown."}],"title":"location","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location"}}}