{"kind":"symbol","identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor\/Abort\/recoverySuggestion-8rnsl","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/vapor\/abort\/recoverysuggestion-8rnsl"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:5Vapor15DebuggableErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:5Vapor5AbortV","symbolKind":"property","extendedModule":"Vapor","modules":[{"name":"Vapor"}],"title":"recoverySuggestion","roleHeading":"Instance Property"},"abstract":[{"text":"A localized message describing how one might recover from the failure.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor","doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor\/Abort","doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor\/Abort\/DebuggableError-Implementations"]]},"references":{"doc://co.pointfree.VaporRouting/documentation/Vapor/Abort/recoverySuggestion-8rnsl":{"kind":"symbol","url":"\/documentation\/vapor\/abort\/recoverysuggestion-8rnsl","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor\/Abort\/recoverySuggestion-8rnsl","role":"symbol","type":"topic","title":"recoverySuggestion","abstract":[{"text":"A localized message describing how one might recover from the failure.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://co.pointfree.VaporRouting/documentation/Vapor/Abort":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Abort","kind":"identifier"}],"abstract":[{"type":"text","text":"Default implementation of "},{"code":"AbortError","type":"codeVoice"},{"type":"text","text":". You can use this as a convenient method for throwing"},{"type":"text","text":" "},{"code":"AbortError","type":"codeVoice"},{"type":"text","text":"s without having to conform your own error-type to "},{"code":"AbortError","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Abort","kind":"identifier"}],"url":"\/documentation\/vapor\/abort","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor\/Abort","title":"Abort"},"doc://co.pointfree.VaporRouting/documentation/Vapor/Abort/DebuggableError-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/vapor\/abort\/debuggableerror-implementations","title":"DebuggableError Implementations","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor\/Abort\/DebuggableError-Implementations","type":"topic"},"doc://co.pointfree.VaporRouting/documentation/Vapor":{"title":"Vapor","abstract":[],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/Vapor","kind":"symbol","url":"\/documentation\/vapor","type":"topic","role":"collection"}}}